### ISSUE TITLE
Errors when using current go.mod (and dependencies)

### ISSUE THREAD

**Issue by ms-clovis** [sisyphsu/slf4go#3]
When simply importing module 
import slog "github.com/go-eden/slf4go"

and using the following 
slog.SetLevel(slog.InfoLevel)
	slog.Debug("Don't see this")
	slog.Info("DO see this")

Here are the errors

# github.com/go-eden/etime
C:\Go_Projs\pkg\mod\github.com\go-eden\etime@v1.0.1\etime_now.go:19:11: cannot use tv.Sec (type int32) as type int64 in return argument
C:\Go_Projs\pkg\mod\github.com\go-eden\etime@v1.0.1\etime_now.go:33:20: invalid operation: tv.Sec * 1000 + int64(tv.Usec) / 1000 (mismatched types int32 and int64)
C:\Go_Projs\pkg\mod\github.com\go-eden\etime@v1.0.1\etime_now.go:47:20: invalid operation: tv.Sec * 1e+06 + int64(tv.Usec) (mismatched types int32 and int64)

# github.com/huandu/go-tls
C:\Go_Projs\pkg\mod\github.com\huandu\go-tls@v0.0.0-20190320055402-ef90f27f86a2\syscall_unix.go:17:17: undefined: syscall.PROT_NONE
C:\Go_Projs\pkg\mod\github.com\huandu\go-tls@v0.0.0-20190320055402-ef90f27f86a2\syscall_unix.go:18:17: undefined: syscall.PROT_READ
C:\Go_Projs\pkg\mod\github.com\huandu\go-tls@v0.0.0-20190320055402-ef90f27f86a2\syscall_unix.go:19:17: undefined: syscall.PROT_WRITE
C:\Go_Projs\pkg\mod\github.com\huandu\go-tls@v0.0.0-20190320055402-ef90f27f86a2\syscall_unix.go:20:17: undefined: syscall.PROT_EXEC
C:\Go_Projs\pkg\mod\github.com\huandu\go-tls@v0.0.0-20190320055402-ef90f27f86a2\syscall_unix.go:30:32: not enough arguments in call to syscall.Syscall
C:\Go_Projs\pkg\mod\github.com\huandu\go-tls@v0.0.0-20190320055402-ef90f27f86a2\syscall_unix.go:30:33: undefined: syscall.SYS_MPROTECT

**Comment by sisyphsu** [comment]
Got it, I will fix it before tomorrow.

**Comment by sisyphsu** [comment]
@ms-clovis I have fix this issue in version `v1.0.4`.

`slf4go` don't use `github.com/go-eden/etime` and `github.com/huandu/go-tls` anymore, now it only requires `github.com/go-eden/common`, which is maintained by myself.

You could run `go get -u -t ./...` to update versions, after that the `go.mod` should like:
```
require (
    ......
    github.com/go-eden/slf4go v1.0.4
)
```

**Comment by ms-clovis** [comment]
Thank you for your prompt attention. I am still getting the following (as part of common)

# github.com/go-eden/common/etime

C:\Go_Projs\pkg\mod\github.com\go-eden\common@v0.1.3\etime\etime_now.go:23:20: invalid operation: tv.Sec * 1000 + int64(tv.Usec) / 1000 (mismatched types int32 and int64)
C:\Go_Projs\pkg\mod\github.com\go-eden\common@v0.1.3\etime\etime_now.go:32:20: invalid operation: tv.Sec * 1e+06 + int64(tv.Usec) (mismatched types int32 and int64)

**Comment by ms-clovis** [comment]
These are the changes necessary in etime_now.go:

func NowMillisecond() int64 {
	var tv syscall.Timeval
	if err := syscall.Gettimeofday(&tv); err != nil {
		return time.Now().UnixNano() / 1e6
	}
	return int64(tv.Sec*1e3) + int64(tv.Usec)/1e3
}

// NowMicrosecond obtains the current microsecond, use syscall for better performance
func NowMicrosecond() int64 {
	var tv syscall.Timeval
	if err := syscall.Gettimeofday(&tv); err != nil {
		return time.Now().UnixNano() / 1e3
	}
	return int64(tv.Sec*1e6) + int64(tv.Usec)
}

**Comment by sisyphsu** [comment]
OK... now I find the reason.

In **linux** and **osx**, the datatype of `syscall.Timeval.Sec` is `int64`, but in **windows**, it is `int32`, this is really unexpected...

I have commit it into the new release `v1.0.5`, you could try it.

Thank you for all.

**Comment by ms-clovis** [comment]
Thank you for your time
