### ISSUE TITLE
combine slf4go and zap?

### ISSUE THREAD

**Issue by phenix3443** [sisyphsu/slf4go#4]
Do you have a plan to do Driver implementation for bridging slf4go and zap?

**Comment by sisyphsu** [comment]
@phenix3443 

Yes, but may not very fast. 

I'm working on another library, which will be done in several weeks, after that, i will back to add more features and drivers for `slf4go`.

If you want to implement a Driver for `slf4go` and `zap`, you can make a pullrequest(which is very welcomed) and publish it at this repo: https://github.com/go-eden/slf4go-zap

Thanks~~

**Comment by phenix3443** [comment]
I has do a simple zap driver, please check the pr

**Comment by sisyphsu** [comment]
Thanks for your PR, i have merged it into `slf4go-zap` ☺
https://github.com/go-eden/slf4go-zap
